name: Publish to NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Compute version from tag
        id: vars
        shell: bash
        run: |
          ref="${GITHUB_REF_NAME}"
          version="${ref#v}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      # 同时打包 Core 与 Analyzer（版本取自 tag）
      - name: Pack FluentPermissions.Core
        run: |
          mkdir -p out
          dotnet pack FluentPermissions/FluentPermissions.Core/FluentPermissions.Core.csproj \
            -c Release -o ./out \
            /p:ContinuousIntegrationBuild=true \
            /p:PackageVersion=${{ steps.vars.outputs.version }}

      - name: Pack FluentPermissions analyzer
        run: |
          dotnet pack FluentPermissions/FluentPermissions/FluentPermissions.csproj \
            -c Release -o ./out \
            /p:ContinuousIntegrationBuild=true \
            /p:PackageVersion=${{ steps.vars.outputs.version }}

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "out/*.nupkg" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate